jenkinsci/jms-messaging-plugin

- Jenkinsfile
> Minor simplifications

- src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/FedMsgMessagingWorker.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/FedMsgMessagingPluginIntegrationTest.java
I need this in order to make correlations from shipshift data to
determine what artifacts a job is *about*.
> Add CI_HEADERS to the env for triggered jobs.

- src/main/java/com/redhat/jenkins/plugins/ci/CIBuildTrigger.java
- src/main/java/com/redhat/jenkins/plugins/ci/ProjectChangeListener.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/MessageProviderMigrator.java
- src/test/java/com/redhat/jenkins/plugins/ci/MigrationTest.java
- src/test/resources/com/redhat/jenkins/plugins/ci/MigrationTest/testAlreadyMigratedConfig/com.redhat.jenkins.plugins.ci.GlobalCIConfiguration.xml
- src/test/resources/com/redhat/jenkins/plugins/ci/MigrationTest/testAlreadyMigratedConfig/config.xml
- src/test/resources/com/redhat/jenkins/plugins/ci/MigrationTest/testAlreadyMigratedConfig/jobs/ci-message-subscriber/config.xml
- src/test/resources/com/redhat/jenkins/plugins/ci/MigrationTest/testAlreadyMigratedConfig/jobs/ci-notifier/config.xml
- src/test/resources/com/redhat/jenkins/plugins/ci/MigrationTest/testAlreadyMigratedConfig/jobs/ci-trigger/config.xml
- Revert previous fix for disabled triggers. Now use onUpdated()
- Now check provider on all startups if empty and fix.
> Fix trigger if disabled and fix migration

- pom.xml
- src/main/java/com/redhat/jenkins/plugins/ci/CIMessageBuilder.java
- src/main/java/com/redhat/jenkins/plugins/ci/CIMessageNotifier.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/FedMsgMessagingWorker.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/JMSMessagingWorker.java
- src/main/java/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSenderStep.java
- src/main/java/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSubscriberStep.java
- src/main/java/com/redhat/utils/MessageUtils.java
- src/main/java/com/redhat/utils/OrderedProperties.java
- src/main/resources/com/redhat/jenkins/plugins/ci/CIMessageBuilder/config.jelly
- src/main/resources/com/redhat/jenkins/plugins/ci/CIMessageBuilder/help-failOnError.html
- src/main/resources/com/redhat/jenkins/plugins/ci/CIMessageNotifier/config.jelly
- src/main/resources/com/redhat/jenkins/plugins/ci/CIMessageNotifier/help-failOnError.html
- src/main/resources/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSenderStep/config.jelly
- src/main/resources/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSenderStep/help-failOnError.html
- src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/FedMsgMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/SharedMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/po/CINotifierBuildStep.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/po/CINotifierPostBuildStep.java
- improve support for env var substitution.
- add failonerror for messaging sending
- add support for replacing tokens using previously defined properties
- refactor pipeline steps so logging and aborting works
- refactor test to reduce duplication
> Refactoring

- src/main/java/com/redhat/jenkins/plugins/ci/CIMessageNotifier.java
- src/main/java/com/redhat/jenkins/plugins/ci/CIMessageSubscriberBuilder.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
- src/main/java/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSenderStep.java
- src/main/java/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSubscriberStep.java
- src/main/java/com/redhat/utils/MessageUtils.java
Update CIMessageSendStep code to use CIMessageNotifier. Add methods to allow calls from pipeline code.
> Update CIMessageSendStep code to use CIMessageNotifier.

- src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/FedMsgMessagingWorker.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/data/FedmsgMessage.java
- For AMQ, message ID needs to be set after send of message
- For FedMsg, re-add msgId that was removed.
> Fix SendResult missing msgId

- src/main/java/com/redhat/jenkins/plugins/ci/CIBuildTrigger.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/FedMsgMessagingWorker.java
- src/main/java/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQSubscriberProviderData.java
- src/main/java/com/redhat/jenkins/plugins/ci/provider/data/FedMsgSubscriberProviderData.java
- src/main/java/com/redhat/jenkins/plugins/ci/provider/data/ProviderData.java
- src/main/resources/com/redhat/jenkins/plugins/ci/CIMessageBuilder/config.jelly
- src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/MigrationIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/po/CIEventTrigger.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/po/CINotifierBuildStep.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/po/CINotifierPostBuildStep.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/po/CISubscriberBuildStep.java
Include JMS headers in MESSAGE_HEADERS.
Fix a minor bug.
Fix a typo.
Fix tests.
> [CID-3280] MESSAGE_HEADERS should include all message headers.

- Jenkinsfile
- pom.xml
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessageWatcher.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingProvider.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/FedMsgMessageWatcher.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/FedMsgMessagingProvider.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/FedMsgMessagingWorker.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/JMSMessageWatcher.java
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/JMSMessagingProvider.java
- src/test/resources/ath-container/Dockerfile
- vnc.sh
Pick up some changes from @olivergondza for testing issues.
Fix testing dependency problems.
> CID-3909: Trigger thread is dying with an unhandled exception.

- src/main/resources/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSenderStep/config.jelly
- src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQPublisherProviderData/ActiveMQPublisherProviderDataDescriptor/amq-publisher.jelly
- src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/FedMsgPublisherProviderData/FedMsgPublisherProviderDataDescriptor/fedmsg-publisher.jelly
[JENKINS-55787](https://issues.jenkins-ci.org/browse/JENKINS-55787)
> [JENKINS-55787] Switch labels from entry to checkbox

- Jenkinsfile
- pom.xml
- src/main/java/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSenderStep.java
- src/main/java/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSubscriberStep.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/FedMsgMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/SharedMessagingPluginIntegrationTest.java
Note that I also update the Jenkins version everywhere to 1.107.3. That's required for the workflow-api-step plugin.  Hopefully it all works....
> Issue 116: sendCIMessage gets stuck running when given nonexistent provider.

- src/main/java/com/redhat/jenkins/plugins/ci/messaging/FedMsgMessagingWorker.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/FedMsgMessagingPluginIntegrationTest.java
> Ensure timestamp is set when sending FedMsg

- src/main/java/com/redhat/jenkins/plugins/ci/CIBuildTrigger.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/FedMsgMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/SharedMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/po/TextParameter.java
> Support Multi-line String parameter for CI_MESSAGE definition

- Jenkinsfile
- src/main/java/com/redhat/jenkins/plugins/ci/CIBuildTrigger.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/FedMsgMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/SharedMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/po/BooleanParameter.java
- Check if job parameters contain BooleanParameter
- Update version of Jenkins needed for testing
fixes #134
> Support Boolean Parameters

- src/main/java/com/redhat/jenkins/plugins/ci/CIBuildTrigger.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/SharedMessagingPluginIntegrationTest.java
> Ensure default values are used for build parameters when triggering

- Jenkinsfile
To prevent huge longs with maven download progress
> Use mvn batch mode

- Jenkinsfile
- pom.xml
- run.sh
- set-java.sh
- src/main/java/com/redhat/jenkins/plugins/ci/messaging/FedMsgMessagingWorker.java
- src/main/resources/com/redhat/jenkins/plugins/ci/integration/docker/fixtures/FedmsgRelayContainer/relay.py
- src/main/resources/com/redhat/jenkins/plugins/ci/integration/docker/fixtures/FedmsgRelayContainer/setup.sh
- src/main/resources/com/redhat/jenkins/plugins/ci/integration/docker/fixtures/JBossAMQContainer/install.sh
- src/test/java/com/redhat/jenkins/plugins/ci/integration/FedMsgMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/docker/fixtures/FedmsgRelayContainer.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/docker/fixtures/JBossAMQContainer.java
- vnc.sh
- new jenkins version
- works with fedora 30 and podman
> Ensure tests work

- src/main/java/com/redhat/jenkins/plugins/ci/CIBuildTrigger.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/FedMsgMessagingPluginIntegrationTest.java
- src/test/java/com/redhat/jenkins/plugins/ci/integration/SharedMessagingPluginIntegrationTest.java
> Correct handling of Boolean Parameters during triggering

- src/main/java/com/redhat/jenkins/plugins/ci/messaging/RabbitMQMessagingWorker.java
> Fix: Incorrect timestamp format

- plugin/src/main/java/com/redhat/jenkins/plugins/ci/CIBuildTrigger.java
- ui-tests/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- ui-tests/src/test/java/com/redhat/jenkins/plugins/ci/integration/SharedMessagingPluginIntegrationTest.java
- ui-tests/src/test/java/com/redhat/jenkins/plugins/ci/integration/po/ChoiceParameter.java
- Set choice parameter value to default value when build is triggered.
Fixes #178
> Do not ignore Select/Choice parameters when triggering builds

- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/form/dropdownInstanceSelector.jelly
- ui-tests/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- ui-tests/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginLockdownIntegrationTest.java
- ui-tests/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginWithFailoverIntegrationTest.java
- ui-tests/src/test/java/com/redhat/jenkins/plugins/ci/integration/SharedMessagingPluginIntegrationTest.java
- ui-tests/src/test/java/com/redhat/jenkins/plugins/ci/integration/docker/fixtures/ActiveMQContainer.java
- ui-tests/src/test/resources/com/redhat/jenkins/plugins/ci/integration/docker/fixtures/ActiveMQContainer/Dockerfile
- ui-tests/src/test/resources/com/redhat/jenkins/plugins/ci/integration/docker/fixtures/FedmsgRelayContainer/Dockerfile
- Additional fixes for test containers (Fedora FedMsg and new ActiveMQ)
Fixes #184
Fixes #146
> Correct presentation of data model for CI Notifier and CI Subscriber

- README.md
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
- plugin/src/main/java/com/redhat/utils/MessageUtils.java
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/CIMessageBuilder/config.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/CIMessageNotifier/config.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/CIMessageSubscriberBuilder/config.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/form/dropdownInstanceSelector.jelly
- ui-tests/pom.xml
- ui-tests/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- ui-tests/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginWithFailoverIntegrationTest.java
- ui-tests/src/test/java/com/redhat/jenkins/plugins/ci/integration/SharedMessagingPluginIntegrationTest.java
- correctly setup data model for display of job configs
Fixes #190
> Correct regression of Selectors disappearing in v1.1.16

- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
Reverts jenkinsci/jms-messaging-plugin#181
> Revert "Allow sending notification to queue when useQueues is true"

- plugin/pom.xml
> Make olivergondza a co-maintainer

- Jenkinsfile
- plugin/code-coverage.sh
- plugin/pom.xml
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/CIBuildTrigger/config.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/form/blockWrapper.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSenderStep/config.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSubscriberStep/config.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQPublisherProviderData/ActiveMQPublisherProviderDataDescriptor/amq-publisher.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQSubscriberProviderData/ActiveMQSubscriberProviderDataDescriptor/amq-subscriber.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/FedMsgPublisherProviderData/FedMsgPublisherProviderDataDescriptor/fedmsg-publisher.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/FedMsgSubscriberProviderData/FedMsgSubscriberProviderDataDescriptor/fedmsg-subscriber.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQPublisherProviderData/RabbitMQPublisherProviderDataDescriptor/rabbitmq-publisher.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQSubscriberProviderData/RabbitMQSubscriberProviderDataDescriptor/rabbitmq-subscriber.jelly
- ui-tests/pom.xml
Migrate UI to use conditional wrapper selecting table or div based on core version.
https://issues.jenkins.io/browse/JENKINS-62863
- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
> JENKINS-62863: Adjust to use divs over tabs in UI

- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/data/RabbitMQMessage.java
- ui-tests/pom.xml
> Fix #218: Do not prefix Rabbit MQ messages with current year

- Jenkinsfile
- plugin/pom.xml
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/threads/CITriggerThread.java
- plugin/src/main/resources/index.html
- plugin/src/main/resources/index.jelly
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginWithFailoverIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/FedMsgMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/RabbitMQMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/SharedMessagingPluginIntegrationTest.java
- pom.xml
- [n/a] Link to relevant issues in GitHub or Jira
- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
- [n/a] Ensure you have provided tests - that demonstrates feature works or fixes the issue
> Depend on Jenkins 2.346.3 and Java 11

- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/RabbitMQMessagingWorker.java
Resolves #262.
- [ X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ X] Ensure that the pull request title represents the desired changelog entry
- [ X] Please describe what you did
- [ X] Link to relevant issues in GitHub or Jira
- [ X] Link to relevant pull requests, esp. upstream and downstream changes
- [ X] Ensure you have provided tests - that demonstrates feature works or fixes the issue
> Use UUID for temporary queue name in RabbitMQ.

- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSubscriberStep.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
> Set message headers variable

- plugin/src/main/java/com/redhat/jenkins/plugins/ci/CIBuildTrigger.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/GlobalCIConfiguration.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/authentication/rabbitmq/SSLCertificateAuthenticationMethod.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingProvider.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/FedMsgMessageWatcher.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/JMSMessageWatcher.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/JMSMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/RabbitMQMessagingProvider.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/RabbitMQMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/checks/MsgCheck.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/threads/FedMsgTriggerThread.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/threads/RabbitMqTriggerThread.java
Fix errors found by SpotBugs.
- [ x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [ x] Please describe what you did
- [ x] Link to relevant issues in GitHub or Jira
- [ x] Link to relevant pull requests, esp. upstream and downstream changes
- [ x] Ensure you have provided tests that demonstrate the feature works or the issue is fixed
> Fix SpotBugs errors.

- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/KafkaMessagingProvider.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/KafkaMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/KafkaProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/KafkaPublisherProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/KafkaSubscriberProviderData.java
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/KafkaPublisherProviderData/KafkaPublisherProviderDataDescriptor/kafka-publisher.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/KafkaPublisherProviderData/help-properties.html
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/KafkaSubscriberProviderData/KafkaSubscriberProviderDataDescriptor/kafka-subscriber.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/KafkaSubscriberProviderData/help-properties.html
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/KafkaMessagingPluginIntegrationTest.java
Add producer and consumer properties for Kafka.
> Add producer and consumer properties for Kafka.

- plugin/src/main/java/com/redhat/jenkins/plugins/ci/CIBuildTrigger.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/FedMsgMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/KafkaMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/RabbitMQMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/threads/CITriggerThreadFactory.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/threads/KafkaTriggerThread.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/FedMsgMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/KafkaMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/ProviderDocker.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/RabbitMQMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/SharedMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/fixtures/KafkaContainer.java
> Refactor tests.

- plugin/src/main/java/com/redhat/jenkins/plugins/ci/CIBuildTrigger.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQPublisherProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQSubscriberProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/KafkaProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/KafkaPublisherProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/KafkaSubscriberProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQPublisherProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQSubscriberProviderData.java
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/CIBuildTrigger/config.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSenderStep/config.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSubscriberStep/config.jelly
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginWithFailoverIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/KafkaMessagingPluginIntegrationTest.java
Fix to work with snippet generator.
> Fix to work with snippet generator.

- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/KafkaMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQPublisherProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQSubscriberProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/KafkaPublisherProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/KafkaSubscriberProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/ProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQPublisherProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQSubscriberProviderData.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/BaseTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/KafkaMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/SharedMessagingPluginIntegrationTest.java
Use snippetizer to generate test script code.
> Use snippetizer to generate test script code.

- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQSubscriberProviderData/ActiveMQSubscriberProviderDataDescriptor/amq-subscriber.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQSubscriberProviderData/RabbitMQSubscriberProviderDataDescriptor/rabbitmq-subscriber.jelly
Fix JENKINS-74469 and JENKINS-74473.
> Fix JENKINS-74469 and JENKINS-74473.

- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
JENKINS-61181: fix use queues for AMQ sending messages.
> JENKINS-61181: fix use queues for AMQ sending messages.

- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/KafkaMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/RabbitMQMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQPublisherProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/KafkaPublisherProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQPublisherProviderData.java
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQPublisherProviderData/RabbitMQPublisherProviderDataDescriptor/rabbitmq-publisher.jelly
Fix save/restore of job steps when configuring.
> Fix save/restore of job steps when configuring.

- plugin/pom.xml
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/CIBuildTrigger.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/CIMessageSubscriberBuilder.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/ActiveMqMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/JMSMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/KafkaMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/RabbitMQMessagingWorker.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSenderStep.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/pipeline/CIMessageSubscriberStep.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQSubscriberProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/KafkaSubscriberProviderData.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQSubscriberProviderData.java
- plugin/src/main/java/com/redhat/utils/MessageUtils.java
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQSubscriberProviderData/ActiveMQSubscriberProviderDataDescriptor/amq-subscriber.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/KafkaSubscriberProviderData/KafkaSubscriberProviderDataDescriptor/kafka-subscriber.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQSubscriberProviderData/RabbitMQSubscriberProviderDataDescriptor/rabbitmq-subscriber.jelly
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/AmqMessagingPluginWithFailoverIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/KafkaMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/RabbitMQMessagingPluginIntegrationTest.java
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/SharedMessagingPluginIntegrationTest.java
> Support passing message content in files.

- plugin/pom.xml
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/authentication/kafka/KafkaAuthenticationMethod.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/authentication/kafka/NoneAuthenticationMethod.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/authentication/kafka/UsernameAuthenticationMethod.java
- plugin/src/main/java/com/redhat/jenkins/plugins/ci/messaging/KafkaMessagingProvider.java
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/authentication/kafka/NoneAuthenticationMethod/NoneAuthenticationMethodDescriptor/none.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/authentication/kafka/UsernameAuthenticationMethod/UsernameAuthenticationMethodDescriptor/help-credentialId.html
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/authentication/kafka/UsernameAuthenticationMethod/UsernameAuthenticationMethodDescriptor/username.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/messaging/KafkaMessagingProvider/config.jelly
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/messaging/KafkaMessagingProvider/help-authenticationMethod.html
- plugin/src/test/java/com/redhat/jenkins/plugins/ci/integration/KafkaMessagingPluginIntegrationTest.java
Add username/password authentication for Kafka provider.
> Add username/password authentication for Kafka provider.

- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQSubscriberProviderData/help-useFiles.html
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/ActiveMQSubscriberProviderData/help-variable.html
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/KafkaSubscriberProviderData/help-useFiles.html
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/KafkaSubscriberProviderData/help-variable.html
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQSubscriberProviderData/help-useFiles.html
- plugin/src/main/resources/com/redhat/jenkins/plugins/ci/provider/data/RabbitMQSubscriberProviderData/help-variable.html
Add help for passing message content by file.
> Add help for passing message content by file.

- plugin/src/main/java/com/redhat/utils/CredentialLookup.java
Look for credentials in all available stores.
> Search for credentials in all stores.

- plugin/pom.xml
> Fix dependencies.
